import QRCode from 'qrcode';

/**
 * Renders a URL to an SVG string, server-side (design §7.2). The QR is
 * generated with this package rather than a third-party image service
 * (`api.qrserver.com`, Google Charts, etc.) because the join URL carries a
 * bearer secret (design §3.7) -- handing it to a third party to render would
 * publish it. The returned string is meant to be passed to a Client
 * Component and rendered via `dangerouslySetInnerHTML`, which is safe here
 * specifically because the SVG is generated by this app's own trusted
 * `qrcode` library from a value this app fully controls, never from
 * unsanitized user input.
 */
export async function generateQrSvg(url: string): Promise<string> {
  return QRCode.toString(url, { type: 'svg' });
}
