-- Past events: the DJ's events, and the songs actually played at them.
-- docs/specs/2026-08-29-past-events-design.md §4 and §5.
--
-- The filename 20260829171500 is pinned by hand rather than generated by
-- `supabase migration new`, and the number is load-bearing at both ends. It
-- must sort AFTER 20260829145349_profiles.sql (which creates the moddatetime
-- extension the trigger below uses) and BEFORE feat/dashboard-data's
-- 20260830000000_event_phase.sql (which ALTERs public.events, created here).
-- The CLI stamps from the UTC clock and would have broken the upper bound
-- after 00:00 UTC. Do not renumber this file to tidy it.

create type public.event_status as enum
  ('draft', 'upcoming', 'live', 'completed', 'cancelled');

create table public.events (
  id            uuid primary key default gen_random_uuid(),
  dj_id         uuid not null references auth.users(id) on delete cascade,
  couple_names  text not null,
  venue         text not null,
  event_date    date not null,
  status        public.event_status not null default 'upcoming',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint couple_names_len check (char_length(couple_names) between 1 and 120),
  constraint venue_len        check (char_length(venue) between 1 and 120)
);

-- The Past events query is exactly this shape: my events, completed, newest
-- first. The two equality columns lead so the lookup is index-backed. The
-- ordering is NOT served by this index when read through the view below --
-- grouping forces a sort above the aggregate -- see design §4.
create index events_dj_status_date_idx
  on public.events (dj_id, status, event_date desc);

create table public.played_songs (
  id            uuid primary key default gen_random_uuid(),
  event_id      uuid not null references public.events(id) on delete cascade,
  position      int  not null,
  title         text not null,
  artist        text not null,
  -- A guest's display name, not a foreign key: guests have no table yet.
  -- NULL means the DJ's own pick. When a guests table exists this gains a
  -- nullable FK ALONGSIDE the retained name -- a recap is a keepsake and has
  -- to still read correctly after a guest row is deleted.
  suggested_by  text,
  played_at     timestamptz,
  constraint position_positive check (position > 0),
  constraint title_len         check (char_length(title)  between 1 and 200),
  constraint artist_len        check (char_length(artist) between 1 and 200),
  constraint suggested_by_len  check (suggested_by is null or char_length(suggested_by) <= 100),
  -- Makes "the playlist, in order" a guarantee rather than a hope. Also
  -- indexes event_id (it leads the key), so no separate index is created.
  unique (event_id, position)
);

alter table public.events       enable row level security;
alter table public.played_songs enable row level security;

-- events: a DJ reaches their own rows and nothing else.
-- `(select auth.uid())` rather than bare auth.uid() so Postgres evaluates it
-- once per statement instead of once per row.
create policy "dj selects own events" on public.events
  for select using ((select auth.uid()) = dj_id);

create policy "dj inserts own events" on public.events
  for insert with check ((select auth.uid()) = dj_id);

-- Both are written explicitly even though they are textually identical, so the intent (what
-- this predicate governs) reads the same for both the pre-image and the post-image rather than
-- relying on Postgres's own USING-as-WITH-CHECK fallback (per the docs: "if no WITH CHECK
-- expression is defined, then the USING expression will be used both to determine which rows
-- are visible and which new rows will be allowed to be added"). Removing the explicit WITH
-- CHECK here would NOT weaken this policy -- Postgres would enforce the identical USING
-- predicate in its place.
create policy "dj updates own events" on public.events
  for update using ((select auth.uid()) = dj_id)
             with check ((select auth.uid()) = dj_id);

-- No delete policy and no delete grant: nothing in this slice deletes an
-- event. The cascade from auth.users runs as the system via the referential-
-- integrity trigger and needs neither.

-- played_songs carries no owner of its own. Its owner is its event's owner,
-- stated once as a predicate rather than denormalised into a dj_id column
-- that could drift away from the event's.
create policy "dj selects songs of own events" on public.played_songs
  for select using (
    exists (select 1 from public.events e
             where e.id = played_songs.event_id
               and e.dj_id = (select auth.uid()))
  );

create policy "dj inserts songs into own events" on public.played_songs
  for insert with check (
    exists (select 1 from public.events e
             where e.id = played_songs.event_id
               and e.dj_id = (select auth.uid()))
  );

-- The `with check` half is what stops a DJ re-parenting one of their own
-- songs onto another DJ's event: `using` admits the row they own, then
-- `with check` evaluates the predicate against the NEW event_id and refuses.
create policy "dj updates songs of own events" on public.played_songs
  for update using (
    exists (select 1 from public.events e
             where e.id = played_songs.event_id
               and e.dj_id = (select auth.uid()))
  ) with check (
    exists (select 1 from public.events e
             where e.id = played_songs.event_id
               and e.dj_id = (select auth.uid()))
  );

grant select, insert, update on public.events       to authenticated;
grant select, insert, update on public.played_songs to authenticated;

-- The hosted project's default ACL grants Dxtm to anon and authenticated on
-- every table `postgres` creates in public. Verified 2026-08-29:
--   select defaclobjtype, defaclacl from pg_default_acl d
--     join pg_namespace n on n.oid = d.defaclnamespace where n.nspname='public'
--   -> 'r': {postgres=arwdDxtm/postgres,anon=Dxtm/postgres,
--            authenticated=Dxtm/postgres,service_role=Dxtm/postgres}
-- D is TRUNCATE, which bypasses RLS entirely. No code path in this app can
-- emit one (PostgREST has no TRUNCATE verb), so this is defence in depth --
-- but profiles revokes it deliberately and these tables must not be laxer.
-- x/t (REFERENCES, TRIGGER) are inert today because authenticated holds
-- USAGE but not CREATE on public. Verified 2026-08-29, read-only:
--   select nspname, nspacl::text from pg_namespace where nspname = 'public'
--   -> {pg_database_owner=UC/pg_database_owner,=U/pg_database_owner,
--       postgres=U/pg_database_owner,anon=U/pg_database_owner,
--       authenticated=U/pg_database_owner,service_role=U/pg_database_owner}
-- anon and authenticated hold U (USAGE), not UC, so neither can create the
-- objects those two privileges would apply to. Revoked anyway, because the
-- point of the pattern is surviving a settings change nobody remembers
-- making.
-- m (MAINTAIN) is revoked on the same grounds: PostgREST has no verb for
-- VACUUM/ANALYZE/CLUSTER/REINDEX, so it is inert too. Left in, `events`
-- would land on authenticated=arwm, and Task 5's ACL check only looks for D.
revoke truncate, references, trigger, maintain on public.events, public.played_songs
  from anon, authenticated;
revoke all on public.events       from anon;
revoke all on public.played_songs from anon;

-- events gets the same updated_at trigger profiles uses. played_songs does
-- not: a played song is a historical fact, not a record that gets edited.
create trigger set_events_updated_at
  before update on public.events
  for each row execute function extensions.moddatetime(updated_at);

-- The screen's song count.
--
-- security_invoker = on is load-bearing. Postgres applies the VIEW OWNER's
-- RLS policies by default, and the owner here is `postgres`, which is not a
-- superuser but does carry rolbypassrls (verified 2026-08-29 against
-- pg_roles: postgres rolsuper=false, rolbypassrls=true). So the default
-- would skip RLS and hand every DJ every other DJ's events. Requires
-- Postgres 15+; this project runs 17.6.
--
-- count(s.id), not count(*): with a left join, count(*) counts the join row
-- that exists even when there are no songs, so an event with no songs would
-- read as 1.
--
-- The `where` is part of the name being true. Without it this returns every
-- event of every status, and anything called past_events_with_counts that
-- contains upcoming events is a name a future reader will trust and be wrong
-- about.
create view public.past_events_with_counts
with (security_invoker = on) as
  select e.id, e.dj_id, e.couple_names, e.venue, e.event_date, e.status,
         count(s.id)::int as songs_played
    from public.events e
    left join public.played_songs s on s.event_id = e.id
   where e.status = 'completed'
   group by e.id;

grant select on public.past_events_with_counts to authenticated;
revoke all   on public.past_events_with_counts from anon;
